services:
  test:
    build: ./Dockerfiles/nvidia/
    container_name: nvidia-container
    volumes:
      - ./:/var/www:z
    working_dir: /var/www
    command: /bin/bash -c "cd /var/www/app && pipenv install && /bin/bash"
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
